#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2017_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py --barcode_type 12 -i Read12018.fastq.gz,Read12017.fastq.gz,Read12016.fastq.gz -b Index2018.fastq.gz,Index2017.fastq.gz,Index2016.fastq.gz -o slout -m map2018.tsv,map2017.tsv,map2016.tsv -q 19

source deactivate
