#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_2d_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "2d plots"
time jackknifed_beta_diversity.py -i open_otus_silva_full/otu_table_mc2_w_tax_no_pynast_failures.biom -o bdiv_jk744 -e 100 -m map_exp.tsv -t open_otus_silva_full/rep_set.tre

source deactivate
