#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_2d_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "2d plots"
time make_2d_plots.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_pc.txt -m map_less.tsv  -o less/2d_plots_final_unweighted

time make_2d_plots.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/weighted_unifrac_pc.txt -m map_less.tsv  -o less/2d_plots_final_weighted

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!

qsub otu_heatmap.pbs
