#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N _2018_core_diversity_analyses
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# diversity analyes
echo "Running Core diversity analyses"
time core_diversity_analyses.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/open_otus_silva_full/otu_table_mc2_w_tax_no_pynast_failures.biom -o cda -m map_less.tsv -t /lustre/home/d411/zcbtmjv/2018_02_smb/final/open_otus_silva_full/rep_set.tre -e 38830

source deactivate

qsub compare_categories_anosim_weighted.pbs
