#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_compare_categories
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "compare"

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SampleLongitude -o less/compare_bioenvlong_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SampleLatitude -o less/compare_bioenvlat_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SampleDepth -o less/compare_bioenvdepth_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SampleFootFall -o less/compare_bioenvfootfall_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m mapless.tsv -c SampleMoisture -o less/compare_bioenvmoisture_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SamplePh -o less/compare_bioenvph_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SamplePotassium -o less/compare_bioenvK_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SampleNitrogen -o less/compare_bioenvN_unweighted

time compare_categories.py --method bioenv -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -c SamplePhosphorus -o less/compare_bioenvP

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!

qsub make_distance_boxplots.pbs
