#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_compare_categories
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "compare"

time group_significance.py -i core_table_50_L2.biom -m map_all.tsv -c SamplePh -o L2/group_ph

time group_significance.py -i core_table_50_L2.biom -m map_all.tsv -c SamplePotassium -o L2/group_K

time group_significance.py -i core_table_50_L2.biom -m map_all.tsv -c SampleNitrogen -o L2/group_N

time group_significance.py -i core_table_50_L2.biom -m map_all.tsv -c SamplePhosphorus -o L2/group_P

time group_significance.py -i core_table_50_L3.biom -m map_all.tsv -c SamplePh -o L3/group_ph

time group_significance.py -i core_table_50_L3.biom -m map_all.tsv -c SampleNitrogen -o L3/group_N

time group_significance.py -i core_table_50_L3.biom -m map_all.tsv -c SamplePotassium -o L3/group_K

time group_significance.py -i core_table_50_L3.biom -m map_all.tsv -c SamplePhosphorus -o L3/group_P

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!

