#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_cr_nojoin_no_golay_serial
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "distance boxplots"
time make_distance_boxplots.py -d /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/unweighted_unifrac_dm.txt -m map_less.tsv -f "SampleLongitude,SampleLatitude,SampleDepth,Year,Month,Day,SampleFootFall,SampleVegetation,SampleWeatherTemp,SampleMoisture,SamplePh,SamplePotassium,SampleNitrogen,SamplePhosphorus" -o less/distance_boxplots_final_unweighted

time make_distance_boxplots.py -d /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/bdiv_even38830/weighted_unifrac_dm.txt -m map_less.tsv -f "SampleLongitude,SampleLatitude,SampleDepth,Year,Month,Day,SampleFootFall,SampleVegetation,SampleWeatherTemp,SampleMoisture,SamplePh,SamplePotassium,SampleNitrogen,SamplePhosphorus" -o less/distance_boxplots_final_weighted 

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!

qsub 2d_plots.pbs
