#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_2d_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "2d plots"
time make_otu_network.py -i otu_table_mc2_w_tax_no_pynast_failures_L2.biom  -o l2_otu_network  -m map_all.tsv

time make_otu_network.py -i otu_table_mc2_w_tax_no_pynast_failures_L3.biom  -o l3_otu_network  -m map_all.tsv

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!

