#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_2d_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# making boxplots
echo "2d plots"
time make_otu_heatmap.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/taxa_plots/table_mc38830_sorted_L4.biom -o less/heatmap4.pdf -m map_less.tsv --dpi 500

time make_otu_heatmap.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/taxa_plots/table_mc38830_sorted_L3.biom -o less/heatmap3.pdf -m map_less.tsv --dpi 500

time make_otu_heatmap.py -i /lustre/home/d411/zcbtmjv/2018_02_smb/final/cda/taxa_plots/table_mc38830_sorted_L2.biom -o less/heatmap2.pdf -m map_less.tsv --dpi 500

source deactivate

# submit picking OTUs parallel job
# please ensure you do not re-submit this script!
