#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N _2018_core_diversity_analyses
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"

# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# diversity analyes
echo "Running Core diversity analyses"
time summarize_taxa.py -i open_otus_silva_all/otu_table_mc2_w_tax_no_pynast_failures.biom -L 2,3 

source deactivate

