#!/bin/bash --login
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=32
#PBS -N 3_picking_OTUs_joined_Reads
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# picking OTUs
echo "Picking OTUs with open reference"
time pick_open_reference_otus.py -i ~/3years/slout/seqs.fna -o ~/3years/otus_open_3years -a -O 16


source deactivate
