#!/bin/bash --login
#PBS -l walltime=2:00:00
#PBS -l select=1:ncpus=32
#PBS -N _2018_joined_Reads
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"

# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# picking OTUs
echo "Picking OTUs with closed reference"
time pick_open_reference_otus.py -i slout/seqs.fna -o final/open_otus_silva_full -a -O 16

source deactivate
