#!/bin/bash --login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_2d_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# setting temporary directory
export TMPDIR=~/qiime_tmp

# loading virtualenv
echo "loading virtualenv"
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate st2

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i ~/sourcetracker/result.biom \
-m ~/sourcetracker/parsed_map.tsv \
-o ~/sourcetracker/tracked \
--sink_rarefaction_depth 1300 \
--source_rarefaction_depth 1300 \

source deactivate
