#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N 2018_Marc_Vangerven_Read3.0
#PBS -A d411-training

cd $PBS_O_WORKDIR

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l) 
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py -i seqprep_assembled.fastq.gz -b seqprep_assembled.fastq_barcodes.fastq  -o slout  -m map_less.tsv  --rev_comp_barcode --rev_comp_mapping_barcodes -q 19

 # counting sequences
echo "Counting sequences"
time count_seqs.py -i slout/seqs.fna

source deactivate

qsub picking_OTUs_Silva.pbs
# submit picking OTUs parallel job
# please ensure you do not re-submit this script!
